   
   
   DIFFRENCE BETWEEN HTTP 1 & HTTP 2

HTTP 1:
     * SLOWER
	 * NETWORK DELAY
	 * PAGE LOADS SLOWER
	 * CONSUME LESS BANDWIDTH
	 * TEXTUAL FORMAT
	 * CLINT RESPONSE TIME IS SLOWER
	 * MULITIPLE TCP CONNECTION
	 
HTTP 2:
	 * FASTER
	 * NO NETWORK DELAY ISSUES
	 * PAGE LOADS FASTER THAN HTTP1
	 * BINARY PROTOCAL
	 * CLINT RESPOSE TIME IS FASTER
	 * SINGLE TCP CONNECTION